using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DFC.App.DiscoverSkillsCareers.Migration.Contacts;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using Newtonsoft.Json.Linq;

namespace DFC.App.DiscoverSkillsCareers.Migration.Services
{
    public class PopulateTestDataService : IMigrationService
    {
        private readonly IDocumentClient destinationDocumentClient;
        private static Random random = new Random();
        
        public PopulateTestDataService(
            IDocumentClient destinationDocumentClient)
        {
            this.destinationDocumentClient = destinationDocumentClient;
        }

        public async Task Start()
        {
            var itemsToInsert = 300000;
            var batchSize = 80;  // 3 at 400, 8 at 1000, 80 at 10,000, 320 at 40,000 - charge is 116 RUs
            var counter = 0;

            while (counter < itemsToInsert)
            {
                var populateTasks = new List<Task>();

                for (int idx = 0, len = batchSize; idx < len; idx++)
                {
                    var assessment = Document.Replace("[id]", RandomString(14)).Replace("[partitionKey]", $"session{counter+idx}");
                    populateTasks.Add(Add(assessment, counter + idx + 1, itemsToInsert));
                }
                
                await Task.WhenAll(populateTasks);
                counter += batchSize;  
            }
        }
        
        private static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray()).ToLower();
        }
        
        private async Task Add(string migratedAssessment, int index, int count)
        {
            Log($"Started creating assessment {index} of {count} - {DateTime.Now:yyyy-MM-dd hh:mm:ss}");
            var start = DateTime.Now;
            
            var resourceResponse = await destinationDocumentClient.CreateDocumentAsync(
                UriFactory.CreateDocumentCollectionUri("DiscoverMySkillsAndCareers", "UserSessions"),
                JObject.Parse(migratedAssessment),
                new RequestOptions());
            
            var charge = resourceResponse.RequestCharge;
            
            Log($"Finished creating assessment {index} of {count} - {DateTime.Now:yyyy-MM-dd hh:mm:ss} - took " +
                $"{(DateTime.Now - start).TotalSeconds} seconds. Charge was {charge} RUs");
        }
        
        private void Log(string message)
        {
            Console.WriteLine(message);
        }

        private string Document =
            @"{
""partitionKey"":""[partitionKey]"",
""id"":""[id]"",
""languageCode"":""en"",
""salt"":""ncs"",
""assessmentState"":{
""questionSetVersion"":""short-201901-24"",
""currentQuestion"":40,
""maxQuestions"":40,
""recordedAnswers"":[
{
""questionId"":""short-201901-24-1"",
""questionNumber"":1,
""questionText"":""Iamcomfortabletellingpeoplewhattheyneedtodo.(DevModified)"",
""traitCode"":""LEADER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:01.4881075Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-2"",
""questionNumber"":2,
""questionText"":""Imakedecisionsquickly"",
""traitCode"":""LEADER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:02.7031997Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-3"",
""questionNumber"":3,
""questionText"":""Iliketotakecontrolofsituations"",
""traitCode"":""LEADER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:04.1328801Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-4"",
""questionNumber"":4,
""questionText"":""Iprefertofollowwhatotherpeoplearedoing"",
""traitCode"":""LEADER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:04.9940341Z"",
""isNegative"":true,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-5"",
""questionNumber"":5,
""questionText"":""Iliketakingresponsibilityforotherpeople"",
""traitCode"":""LEADER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:05.9289619Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-6"",
""questionNumber"":6,
""questionText"":""IsetmyselftargetswhenIhavethingstodo,andusuallymeetthem"",
""traitCode"":""DRIVER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:06.9196111Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-7"",
""questionNumber"":7,
""questionText"":""Iliketoseethingsthroughtotheend"",
""traitCode"":""DRIVER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:08.0040701Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-8"",
""questionNumber"":8,
""questionText"":""IthinkIamacompetitiveperson"",
""traitCode"":""DRIVER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:09.1813247Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-9"",
""questionNumber"":9,
""questionText"":""Doingwellinacareermotivatesme"",
""traitCode"":""DRIVER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:10.0443537Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-10"",
""questionNumber"":10,
""questionText"":""Isetmyselfgoalsinlife"",
""traitCode"":""DRIVER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:10.9650543Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-11"",
""questionNumber"":11,
""questionText"":""Iamcomfortabletalkingpeoplearoundtomywayofthinking"",
""traitCode"":""INFLUENCER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:11.9615596Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-12"",
""questionNumber"":12,
""questionText"":""Iamgoodatcomingtoanagreementwithotherpeople"",
""traitCode"":""INFLUENCER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:12.9908442Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-13"",
""questionNumber"":13,
""questionText"":""Iamcomfortabletalkinginfrontofagroupofpeople"",
""traitCode"":""INFLUENCER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:13.9137679Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-14"",
""questionNumber"":14,
""questionText"":""Ilikemeetingnewpeople"",
""traitCode"":""INFLUENCER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:14.8522206Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-15"",
""questionNumber"":15,
""questionText"":""Ifindithardtounderstandotherpeople'spointofview"",
""traitCode"":""INFLUENCER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:15.7606256Z"",
""isNegative"":true,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-16"",
""questionNumber"":16,
""questionText"":""Iliketohelpotherpeople"",
""traitCode"":""HELPER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:16.9943349Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-17"",
""questionNumber"":17,
""questionText"":""Ienjoyworkingwithotherpeoplearoundme"",
""traitCode"":""HELPER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:17.8706128Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-18"",
""questionNumber"":18,
""questionText"":""Iwanttomakethingsbetterforpeople"",
""traitCode"":""HELPER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:18.7348542Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-19"",
""questionNumber"":19,
""questionText"":""IwillgetinvolvedifIthinkIcanhelp"",
""traitCode"":""HELPER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:19.6572851Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-20"",
""questionNumber"":20,
""questionText"":""Iamcomfortablehearingotherpeople'sproblems"",
""traitCode"":""HELPER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:20.5279386Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-21"",
""questionNumber"":21,
""questionText"":""Iliketoworkoutcomplicatedthings"",
""traitCode"":""ANALYST"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:22.1402201Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-22"",
""questionNumber"":22,
""questionText"":""Iliketogettothecentreoftheissue"",
""traitCode"":""ANALYST"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:23.366244Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-23"",
""questionNumber"":23,
""questionText"":""Ilikeworkingwithfacts"",
""traitCode"":""ANALYST"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:24.1892897Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-24"",
""questionNumber"":24,
""questionText"":""Ilikeworkingwithnumbers"",
""traitCode"":""ANALYST"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:25.1540379Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-25"",
""questionNumber"":25,
""questionText"":""Ienjoylearningnewthings"",
""traitCode"":""ANALYST"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:26.1793881Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-26"",
""questionNumber"":26,
""questionText"":""Ienjoycomingupwithnewwaysofdoingthings"",
""traitCode"":""CREATOR"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:27.3603582Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-27"",
""questionNumber"":27,
""questionText"":""Itrytothinkdifferentlytoothers"",
""traitCode"":""CREATOR"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:28.4838694Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-28"",
""questionNumber"":28,
""questionText"":""Iliketousemyimaginationtocreatenewthings"",
""traitCode"":""CREATOR"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:29.3974943Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-29"",
""questionNumber"":29,
""questionText"":""Iliketotrynewthings"",
""traitCode"":""CREATOR"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:30.3115086Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-30"",
""questionNumber"":30,
""questionText"":""Ienjoycreativeactivities"",
""traitCode"":""CREATOR"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:31.2611342Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-31"",
""questionNumber"":31,
""questionText"":""Iliketofocusondetails"",
""traitCode"":""ORGANISER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:32.3570638Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-32"",
""questionNumber"":32,
""questionText"":""IplanmydaysoIcanusemytimebest"",
""traitCode"":""ORGANISER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:33.2882071Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-33"",
""questionNumber"":33,
""questionText"":""Ilikedoingthingsinacarefulorder"",
""traitCode"":""ORGANISER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:34.867319Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-34"",
""questionNumber"":34,
""questionText"":""Iliketofollowrulesandprocesses"",
""traitCode"":""ORGANISER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:36.0633806Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-35"",
""questionNumber"":35,
""questionText"":""IfeelrestrictedwhenIhavetofollowaroutine"",
""traitCode"":""ORGANISER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:37.0538746Z"",
""isNegative"":true,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-36"",
""questionNumber"":36,
""questionText"":""IliketoseetheresultsoftheworkIdo"",
""traitCode"":""DOER"",
""selectedOption"":0,
""answeredDt"":""2022-05-24T12:15:37.8843543Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-37"",
""questionNumber"":37,
""questionText"":""Iliketogetinvolvedinmakingthings"",
""traitCode"":""DOER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:38.7408611Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-38"",
""questionNumber"":38,
""questionText"":""Ienjoygettinginvolvedinpracticaltasks"",
""traitCode"":""DOER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:39.6549385Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-39"",
""questionNumber"":39,
""questionText"":""Ilikeworkingwithmyhandsortools"",
""traitCode"":""DOER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:40.5299979Z"",
""isNegative"":false,
""questionSetVersion"":""short-201901-24""
},
{
""questionId"":""short-201901-24-40"",
""questionNumber"":40,
""questionText"":""Ienjoyplanningataskmorethanactuallydoingit"",
""traitCode"":""DOER"",
""selectedOption"":4,
""answeredDt"":""2022-05-24T12:15:41.4637829Z"",
""isNegative"":true,
""questionSetVersion"":""short-201901-24""
}
],
""completeDt"":""2022-05-24T12:15:41.4637973Z""
},
""filteredAssessmentState"":{
""jobCategories"":[
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Speaking,VerbalAbilities"",
""QuestionId"":""filtered-default-67-46"",
""QuestionNumber"":1
},
{
""Skill"":""Cooperation"",
""QuestionId"":""filtered-default-67-8"",
""QuestionNumber"":2
},
{
""Skill"":""Initiative"",
""QuestionId"":""filtered-default-67-15"",
""QuestionNumber"":3
},
{
""Skill"":""Adaptability/Flexibility"",
""QuestionId"":""filtered-default-67-3"",
""QuestionNumber"":4
},
{
""Skill"":""ReadingComprehension"",
""QuestionId"":""filtered-default-67-85"",
""QuestionNumber"":5
}
],
""jobCategoryName"":""Creativeandmedia"",
""jobCategoryCode"":""CAM"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Cooperation"",
""QuestionId"":""filtered-default-67-8"",
""QuestionNumber"":1
},
{
""Skill"":""SelfControl"",
""QuestionId"":""filtered-default-67-42"",
""QuestionNumber"":2
},
{
""Skill"":""Initiative"",
""QuestionId"":""filtered-default-67-15"",
""QuestionNumber"":3
},
{
""Skill"":""FineManipulativeAbilities"",
""QuestionId"":""filtered-default-67-12"",
""QuestionNumber"":4
}
],
""jobCategoryName"":""Constructionandtrades"",
""jobCategoryCode"":""CAT"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""SelfControl"",
""QuestionId"":""filtered-default-67-42"",
""QuestionNumber"":1
},
{
""Skill"":""Speaking,VerbalAbilities"",
""QuestionId"":""filtered-default-67-46"",
""QuestionNumber"":2
},
{
""Skill"":""Cooperation"",
""QuestionId"":""filtered-default-67-8"",
""QuestionNumber"":3
}
],
""jobCategoryName"":""Sportsandleisure"",
""jobCategoryCode"":""SAL"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""AnalyticalThinking"",
""QuestionId"":""filtered-default-67-4"",
""QuestionNumber"":1
},
{
""Skill"":""ReadingComprehension"",
""QuestionId"":""filtered-default-67-85"",
""QuestionNumber"":2
},
{
""Skill"":""Persistence"",
""QuestionId"":""filtered-default-67-32"",
""QuestionNumber"":3
}
],
""jobCategoryName"":""Computing,technologyanddigital"",
""jobCategoryCode"":""CTAD"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Cooperation"",
""QuestionId"":""filtered-default-67-8"",
""QuestionNumber"":1
},
{
""Skill"":""VerbalAbilities"",
""QuestionId"":""filtered-default-67-53"",
""QuestionNumber"":2
},
{
""Skill"":""SelfControl"",
""QuestionId"":""filtered-default-67-42"",
""QuestionNumber"":3
},
{
""Skill"":""FineManipulativeAbilities"",
""QuestionId"":""filtered-default-67-12"",
""QuestionNumber"":4
}
],
""jobCategoryName"":""Manufacturing"",
""jobCategoryCode"":""MANUF"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""AnalyticalThinking"",
""QuestionId"":""filtered-default-67-4"",
""QuestionNumber"":1
},
{
""Skill"":""QuantitativeAbilities,MathematicsKnowledge"",
""QuestionId"":""filtered-default-67-38"",
""QuestionNumber"":2
},
{
""Skill"":""ReadingComprehension"",
""QuestionId"":""filtered-default-67-85"",
""QuestionNumber"":3
},
{
""Skill"":""Speaking,VerbalAbilities"",
""QuestionId"":""filtered-default-67-46"",
""QuestionNumber"":4
}
],
""jobCategoryName"":""Scienceandresearch"",
""jobCategoryCode"":""SAR"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Speaking,VerbalAbilities"",
""QuestionId"":""filtered-default-67-46"",
""QuestionNumber"":1
},
{
""Skill"":""Cooperation"",
""QuestionId"":""filtered-default-67-8"",
""QuestionNumber"":2
},
{
""Skill"":""Initiative"",
""QuestionId"":""filtered-default-67-15"",
""QuestionNumber"":3
},
{
""Skill"":""ReadingComprehension"",
""QuestionId"":""filtered-default-67-85"",
""QuestionNumber"":4
}
],
""jobCategoryName"":""Managerial"",
""jobCategoryCode"":""MANAG"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Speaking,VerbalAbilities"",
""QuestionId"":""filtered-default-67-46"",
""QuestionNumber"":1
},
{
""Skill"":""QuantitativeAbilities,MathematicsKnowledge"",
""QuestionId"":""filtered-default-67-38"",
""QuestionNumber"":2
},
{
""Skill"":""ReadingComprehension"",
""QuestionId"":""filtered-default-67-85"",
""QuestionNumber"":3
}
],
""jobCategoryName"":""Businessandfinance"",
""jobCategoryCode"":""BAF"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Speaking,VerbalAbilities"",
""QuestionId"":""filtered-default-67-46"",
""QuestionNumber"":1
},
{
""Skill"":""StressTolerance"",
""QuestionId"":""filtered-default-67-47"",
""QuestionNumber"":2
},
{
""Skill"":""SelfControl"",
""QuestionId"":""filtered-default-67-42"",
""QuestionNumber"":3
}
],
""jobCategoryName"":""Lawandlegal"",
""jobCategoryCode"":""LAL"",
""currentQuestion"":1
},
{
""questionSetVersion"":""filtered-default-67"",
""questions"":[
{
""Skill"":""Cooperation"",
""QuestionId"":""filtered-default-67-8"",
""QuestionNumber"":1
},
{
""Skill"":""SelfControl"",
""QuestionId"":""filtered-default-67-42"",
""QuestionNumber"":2
}
],
""jobCategoryName"":""Deliveryandstorage"",
""jobCategoryCode"":""DAS"",
""currentQuestion"":1
}
],
""recordedAnswers"":[],
""currentFilterAssessmentCode"":null,
""completeDt"":null
},
""resultData"":{
""traits"":[
{
""traitCode"":""LEADER"",
""traitName"":""Leader"",
""traitText"":""youliketoleadotherpeopleandaregoodattakingcontrolofsituations"",
""totalScore"":6
},
{
""traitCode"":""INFLUENCER"",
""traitName"":""Influencer"",
""traitText"":""youaresociableandfinditeasytounderstandpeople"",
""totalScore"":6
},
{
""traitCode"":""ANALYST"",
""traitName"":""Analyst"",
""traitText"":""youlikedealingwithcomplicatedproblemsorworkingwithnumbers"",
""totalScore"":6
},
{
""traitCode"":""CREATOR"",
""traitName"":""Creator"",
""traitText"":""youareacreativepersonandenjoycomingupwithnewwaysofdoingthings"",
""totalScore"":6
},
{
""traitCode"":""DRIVER"",
""traitName"":""Driver"",
""traitText"":""youaremotivated,setyourselfpersonalgoalsandarecomfortablecompetingwithotherpeople"",
""totalScore"":2
},
{
""traitCode"":""ORGANISER"",
""traitName"":""Organiser"",
""traitText"":""youliketoplanthingsandarewellorganised"",
""totalScore"":2
},
{
""traitCode"":""DOER"",
""traitName"":""Doer"",
""traitText"":""youareapracticalpersonandenjoygettingthingsdone"",
""totalScore"":2
}
],
""jobFamilies"":[
{
""jobFamilyCode"":""CAM"",
""jobFamilyName"":""Creativeandmedia"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""creative-and-media"",
""traitsTotal"":14,
""total"":14,
""normalizedTotal"":4.666666666666667,
""TraitValues"":[
{
""traitCode"":""CREATOR"",
""total"":6,
""normalizedTotal"":2
},
{
""traitCode"":""DOER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""ANALYST"",
""total"":6,
""normalizedTotal"":2
}
],
""filterAssessment"":null,
""totalQuestions"":5,
""resultsShown"":false
},
{
""jobFamilyCode"":""CAT"",
""jobFamilyName"":""Constructionandtrades"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""construction-and-trades"",
""traitsTotal"":14,
""total"":14,
""normalizedTotal"":4.666666666666667,
""TraitValues"":[
{
""traitCode"":""CREATOR"",
""total"":6,
""normalizedTotal"":2
},
{
""traitCode"":""DOER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""ANALYST"",
""total"":6,
""normalizedTotal"":2
}
],
""filterAssessment"":null,
""totalQuestions"":4,
""resultsShown"":false
},
{
""jobFamilyCode"":""SAL"",
""jobFamilyName"":""Sportsandleisure"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""sports-and-leisure"",
""traitsTotal"":14,
""total"":14,
""normalizedTotal"":4.666666666666667,
""TraitValues"":[
{
""traitCode"":""CREATOR"",
""total"":6,
""normalizedTotal"":2
},
{
""traitCode"":""ANALYST"",
""total"":6,
""normalizedTotal"":2
},
{
""traitCode"":""DRIVER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
}
],
""filterAssessment"":null,
""totalQuestions"":3,
""resultsShown"":false
},
{
""jobFamilyCode"":""CTAD"",
""jobFamilyName"":""Computing,technologyanddigital"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""computing-technology-and-digital"",
""traitsTotal"":12,
""total"":12,
""normalizedTotal"":6,
""TraitValues"":[
{
""traitCode"":""CREATOR"",
""total"":6,
""normalizedTotal"":3
},
{
""traitCode"":""ANALYST"",
""total"":6,
""normalizedTotal"":3
}
],
""filterAssessment"":null,
""totalQuestions"":3,
""resultsShown"":false
},
{
""jobFamilyCode"":""MANUF"",
""jobFamilyName"":""Manufacturing"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""manufacturing"",
""traitsTotal"":10,
""total"":10,
""normalizedTotal"":3.3333333333333335,
""TraitValues"":[
{
""traitCode"":""ANALYST"",
""total"":6,
""normalizedTotal"":2
},
{
""traitCode"":""DRIVER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""ORGANISER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
}
],
""filterAssessment"":null,
""totalQuestions"":4,
""resultsShown"":false
},
{
""jobFamilyCode"":""SAR"",
""jobFamilyName"":""Scienceandresearch"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""science-and-research"",
""traitsTotal"":10,
""total"":10,
""normalizedTotal"":3.3333333333333335,
""TraitValues"":[
{
""traitCode"":""ANALYST"",
""total"":6,
""normalizedTotal"":2
},
{
""traitCode"":""DRIVER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""ORGANISER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
}
],
""filterAssessment"":null,
""totalQuestions"":4,
""resultsShown"":false
},
{
""jobFamilyCode"":""MANAG"",
""jobFamilyName"":""Managerial"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""managerial"",
""traitsTotal"":8,
""total"":8,
""normalizedTotal"":4,
""TraitValues"":[
{
""traitCode"":""DRIVER"",
""total"":2,
""normalizedTotal"":1
},
{
""traitCode"":""LEADER"",
""total"":6,
""normalizedTotal"":3
}
],
""filterAssessment"":null,
""totalQuestions"":4,
""resultsShown"":false
},
{
""jobFamilyCode"":""BAF"",
""jobFamilyName"":""Businessandfinance"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""business-and-finance"",
""traitsTotal"":6,
""total"":6,
""normalizedTotal"":2,
""TraitValues"":[
{
""traitCode"":""DOER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""DRIVER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""ORGANISER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
}
],
""filterAssessment"":null,
""totalQuestions"":3,
""resultsShown"":false
},
{
""jobFamilyCode"":""LAL"",
""jobFamilyName"":""Lawandlegal"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""law-and-legal"",
""traitsTotal"":6,
""total"":6,
""normalizedTotal"":2,
""TraitValues"":[
{
""traitCode"":""DOER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""DRIVER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
},
{
""traitCode"":""ORGANISER"",
""total"":2,
""normalizedTotal"":0.6666666666666666
}
],
""filterAssessment"":null,
""totalQuestions"":3,
""resultsShown"":false
},
{
""jobFamilyCode"":""DAS"",
""jobFamilyName"":""Deliveryandstorage"",
""jobFamilyText"":"""",
""jobFamilyUrl"":""delivery-and-storage"",
""traitsTotal"":4,
""total"":4,
""normalizedTotal"":2,
""TraitValues"":[
{
""traitCode"":""DOER"",
""total"":2,
""normalizedTotal"":1
},
{
""traitCode"":""ORGANISER"",
""total"":2,
""normalizedTotal"":1
}
],
""filterAssessment"":null,
""totalQuestions"":2,
""resultsShown"":false
}
],
""traitsscores"":[
{
""traitCode"":""LEADER"",
""traitName"":""Leader"",
""traitText"":""youliketoleadotherpeopleandaregoodattakingcontrolofsituations"",
""totalScore"":6
},
{
""traitCode"":""INFLUENCER"",
""traitName"":""Influencer"",
""traitText"":""youaresociableandfinditeasytounderstandpeople"",
""totalScore"":6
},
{
""traitCode"":""ANALYST"",
""traitName"":""Analyst"",
""traitText"":""youlikedealingwithcomplicatedproblemsorworkingwithnumbers"",
""totalScore"":6
},
{
""traitCode"":""CREATOR"",
""traitName"":""Creator"",
""traitText"":""youareacreativepersonandenjoycomingupwithnewwaysofdoingthings"",
""totalScore"":6
},
{
""traitCode"":""DRIVER"",
""traitName"":""Driver"",
""traitText"":""youaremotivated,setyourselfpersonalgoalsandarecomfortablecompetingwithotherpeople"",
""totalScore"":2
},
{
""traitCode"":""ORGANISER"",
""traitName"":""Organiser"",
""traitText"":""youliketoplanthingsandarewellorganised"",
""totalScore"":2
},
{
""traitCode"":""DOER"",
""traitName"":""Doer"",
""traitText"":""youareapracticalpersonandenjoygettingthingsdone"",
""totalScore"":2
},
{
""traitCode"":""HELPER"",
""traitName"":""Helper"",
""traitText"":""youenjoyhelpingandlisteningtootherpeople"",
""totalScore"":-2
}
]
},
""startedDt"":""2022-05-24T12:14:59.4404715+00:00"",
""assessmentType"":""short"",
""lastUpdatedDt"":""2022-05-24T12:15:42.5504037Z"",
""completeDt"":""2022-05-24T12:15:41.4637973Z""
}
";
    }
}