variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'     
  SolutionBaseName: 'DFC.App.DiscoverSkillsCareers'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.8.5
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  #Build and test Azure resources
  - job: ARMResources
    pool:
      name: NCS - CI and CD
      demands:
      - PowerShell
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)

    - task: CopyFiles@2
      displayName: 'Copy Arm Templates to Staging'
      inputs:
        TargetFolder: $(build.artifactstagingdirectory)/PageRegistrations
        SourceFolder: '$(Build.SourcesDirectory)\PageRegistration'
        Contents: |
          *.json

    - task: PublishPipelineArtifact@0
      displayName: Publish Pipeline Artifact
      condition: ${{ parameters.PublishPipelineArtifact }}
      inputs:
        targetPath: $(build.artifactstagingdirectory)/PageRegistrations
        artifactName: ${{ parameters.SolutionBaseName }}.PageRegistrations

  #Build and test application
  - job: BuildTestAndAnalyze
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        TestSuffix: UnitTests
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true